### model params
Model:
  in_channels: 3
  out_channels: 3
  model_channels: 128
  attention_resolutions: [2, ]
  num_res_blocks: 2
  dropout: 0.1
  channel_mult: [1, 2, 2, 2]
  conv_resample: True
  num_heads: 4

### dataset params
Dataset:
  # Deciding which dataset to use, must be one of {'mnist', 'cifar', 'custom'}.
  dataset: "cifar"
  # If mnist and cifar datasets, whether to use the training set.
  train: True
  # Folder of data sets. When `dataset = custom`, this parameter can be a list with different folders.
  # Then all images in the list with suffixes in `suffix` in the folder will be loaded.
  data_path: "./data"
  # If mnist and cifar datasets, whether to download it.
  download: True
  # If mnist dataset, image_size is [28, 28]. If cifar dataset, image_size is [32, 32]. If custom, specify as needed.
  image_size: [ 32, 32 ]

  # If custom dataset, what is the mode of the image. must be one of {'RGB', 'L', 'CMYK'}.
  mode: "RGB"
  # If custom dataset, decide what suffix to load for the image.
  suffix: ["png", "jpg"]

  # parameters for torch.utils.data.DataLoader
  batch_size: 64
  shuffle: True
  drop_last: True
  pin_memory: True
  num_workers: 4

### trainer params
Trainer:
  # sample time steps
  T: 1000
  beta: [0.0001, 0.02]


### callback params
Callback:
  # The save path for checkpoint.
  filepath: "./checkpoint/cifar10.pth"
  # Frequency of checkpoint saving.
  save_freq: 1

### train params
device: "cuda:0"
epochs: 1000
# Whether to continue training, True or False
consume: False
# If continue training, which checkpoint to load
consume_path: "./checkpoint/cifar10.pth"

### optimizer params
lr: 0.0002
